// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3

package types

type GetLongUrlRequest struct {
	ShortUrl string `json:"short_url"`
}

type GetLongUrlResponse struct {
	Url string `json:"url"`
}

type GetShortUrlRequest struct {
	Url string `json:"url"`
}

type GetShortUrlResponse struct {
	ShortUrl string `json:"short_url"`
}
