// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.3
// Source: transform.proto

package server

import (
	"context"

	"github.com/zyyujkkj/shorturl-service/rpc/transform/internal/logic"
	"github.com/zyyujkkj/shorturl-service/rpc/transform/internal/svc"
	"github.com/zyyujkkj/shorturl-service/rpc/transform/transform"
)

type TransformServer struct {
	svcCtx *svc.ServiceContext
	transform.UnimplementedTransformServer
}

func NewTransformServer(svcCtx *svc.ServiceContext) *TransformServer {
	return &TransformServer{
		svcCtx: svcCtx,
	}
}

func (s *TransformServer) GetShortUrl(ctx context.Context, in *transform.GetShortUrlRequest) (*transform.GetShortUrlResponse, error) {
	l := logic.NewGetShortUrlLogic(ctx, s.svcCtx)
	return l.GetShortUrl(in)
}

func (s *TransformServer) GetLongUrl(ctx context.Context, in *transform.GetLongUrlRequest) (*transform.GetLongUrlResponse, error) {
	l := logic.NewGetLongUrlLogic(ctx, s.svcCtx)
	return l.GetLongUrl(in)
}
